backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "programs"
    label: "Programs"
    folder: "src/pages/programs"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "generic-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "image", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "about"
    label: "About"
    folder: "src/pages/about"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "generic-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "image", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "get-involved"
    label: "Get Involved"
    folder: "src/pages/get-involved"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "select",
          options: ["generic-page", "special"],
          default: "generic-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "image", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }


     
      
      
     
